apiVersion: v1
kind: Secret
metadata:
  name: guacamole
  namespace: guacamole
type: Opaque
stringData:
  database: guacamole
  user_login: guacamole
  user_password: <password>
  mysql_root_password: <password>

